# Generated by Django 5.0.1 on 2024-02-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_address_prefecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='stripe_customer_id',
            new_name='product_id',
        ),
    ]
